POST https://localhost:5000/posts/create
content-type: application/json

{
    "title": "Memory 1",
    "description": "Woow amazing",
    "creator": "Finitix",
    "tags": ["memory", "fpv", "tech"],
    "comments": ["This was so cool"]
}